### ISSUE TITLE
Add a spike for controlling a LineFollowing light

### ISSUE THREAD

**Issue by Kaedon2619** [The-Charge/Resistance2019#7]
Add a spike through robot builder, than have it turn on when any line following sensor is triggered. This could be done with a default command.

**Comment by Kaedon2619** [comment]
Electrical notified us that line they wired some LEDs that need to be always enabled: Ashwin reprogrammed this.

**Comment by AshwinS27** [comment]
The spike works but the robot isn't connected to sensors or any dedicated lights for the spike.
